### ISSUE TITLE
cpu or gpu

### ISSUE THREAD

**Issue by jacosmuts** [MProx/deep_q_learning#1]
Hello 

running your code after seeing your article on reddit.

It seems to be using cpu and not gpu.

I am completely new to tensorflow, any idea why i see this behaviour?

**Comment by MProx** [comment]
Hi!

Thanks for the interest. Firstly, I recently made some minor modifications so I recommend cloning the latest version of this repository. 

Secondly, in order to use the GPU, you need to do the following:
(a) make sure your system has a GPU available - I think TensorFlow only supports Nvidia GPUs currently but I might be wrong
(b) make sure you've installed the correct version of TensorFlow that includes GPU support. Instructions for installing TensorFlow 2.0 with GPU can be found here:
https://www.tensorflow.org/install/gpu
I recommend using TensorFlow 2.0, which was just released as the latest stable version. 

Let me know how it goes.

**Comment by MProx** [comment]
Also,I just noticed we're both from South Africa :) 
Hi from Cape Town.

**Comment by jacosmuts** [comment]
Hello, Cape Town (from Pretoria, though I often visit Cape Town).

First off I'm a hobbyist so I'm way behind the curve on what you are doing. 

I am using TensorFlow 2 with GPU enabled and tensorflow can see my GPU. I just couldn't see the load on the GPU while training - basically no load. I will investigate more later tonight and update what I find.

Thanks
Jaco

**Comment by MProx** [comment]
I'm also a hobbyist, but I've been tinkering for a few years now so I've
picked up a few things.

Right now, the only GPU I have available to me is very old (in my laptop).
It's entirely possible that the pre-processing and other computation
applies too much computational overhead such that newer GPUs are barely
loaded at all. The training part of the script is invoked very frequently
with comparatively small number of training samples, and a lot of
computation happens between calls. so it's possible that the GPU doesn't
actually add much benefit.

When you first run the script, it should tell you in the first few lines of
output if there is a GPU available (or will give a warning if no GPUs are
available and it's running on CPU).
